# https://community.home-assistant.io/t/splitting-yaml-files-access-to-secrets-in-esphome-subfolders/158273/2
# https://community.home-assistant.io/t/advice-creating-an-esphome-custom-component-for-alphanumeric-led-display/175848

# docker run --rm -v "${PWD}:/config" -it esphome/esphome weightscale.yaml run

esphome:
  name: weightscale
  platform: ESP8266
  board: d1_mini
  libraries: "2012"

# Not needed
#<<: !include secrets.yaml

wifi:
  # Old address
  #use_address: !secret wifi_manual_addr

  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret esp_ssid
    password: !secret esp_password
    ap_timeout: 5min

captive_portal:

web_server:
  port: 80

# Enable logging
logger:
  level: DEBUG

mqtt:
  broker: !secret broker_addr
  port: !secret broker_port

ota:
  safe_mode: False

sensor:
  - platform: hx711
    name: "HX711 Value"
    dout_pin: D2
    clk_pin: D1
    #gain: 128
    update_interval: 10s
    filters:
      - calibrate_linear:
          - 310123 -> 0
          - 243934 -> 3000
          - -1291565 -> 75000
    unit_of_measurement: g


# TODO: ht16k33 display output

i2c:    
  sda: D2
  scl: D1

display:
  - platform: ht16k33_alpha
    address: 0x70
    scroll: true
    scroll_speed: 250ms
    scroll_dwell: 2s
    scroll_delay: 3
    lambda: |-
      it.print("1234");
